University of Michigan - ROB 101 Computational Linear Algebra

# Homework 2: Vectors, Matrices and Linear Systems

**For this assignment, fill in the code blocks as directed to achieve the desired output.**

### Problem 1.
**a)  Create a row vector with a descriptive name that contains the numbers 1 through 10**

In [1]:
#vectorName = #fill in this line with your code to build the vector

Vec1 = [1 2 3 4 5 6 7 8 9 10]

#output should be
#1 2 3 4 5 6 7 8 9 10

1×10 Matrix{Int64}:
 1  2  3  4  5  6  7  8  9  10

**b) Create a column vector that contains the numbers 11 through 20**

In [2]:
#vectorName = #fill this in

Vec2 = [11; 12; 13; 14; 15; 16; 17; 18; 19; 20]

#output should be
#11 
#12
#13
#14
#15
#16
#17
#18
#19
#20

10-element Vector{Int64}:
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20

**Note: Other ways to build vectors**
* Range notation n:k:m will start at n and take steps of size k to reach m.  Use collect(n:k:m) to make it into a vector
* A[:] converts a matrix A to a vector
* diag() returns the diagonal elements of a matrix as a vector

### Problem 2.
Use indexing [] to return the "panda".  Keep in mind that Julia indexes refer to the location in a vector.

In [3]:
animalsVector = ["lemur", "elephant", "tiger", "panda", "zebra", "cuttlefish"]
myPanda = animalsVector[4]

"panda"

### Problem 3.
**a) Create a matrix of zeros with 4 rows and 7 columns**

In [5]:
zeroMat = zeros(4,7)

4×7 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

**b) Create a matrix of random numbers from a standard normal distribution that will return (17, 8) from this code block**

In [10]:
A = rand(17,8)#fill in.  Hint: check out the cell below for some helpful hints

#(nrow, ncol) = size(A) #do not change this line!

17×8 Matrix{Float64}:
 0.617721   0.106443  0.415435   …  0.651696   0.0557008  0.496906
 0.915      0.365365  0.0881913     0.29877    0.358347   0.476217
 0.867309   0.684491  0.266962      0.986159   0.86754    0.799666
 0.754289   0.667762  0.528298      0.332884   0.0230342  0.017658
 0.38527    0.588045  0.291151      0.969781   0.792107   0.196108
 0.828888   0.759559  0.148814   …  0.96405    0.907659   0.91737
 0.0507813  0.72363   0.45106       0.901472   0.738588   0.177309
 0.449213   0.443146  0.819769      0.367396   0.714136   0.82015
 0.0898777  0.933678  0.117053      0.311208   0.1281     0.306203
 0.954341   0.60772   0.457079      0.0388646  0.024285   0.5949
 0.701708   0.193668  0.569451   …  0.932266   0.80338    0.55249
 0.920437   0.845762  0.735444      0.720069   0.406097   0.031741
 0.340766   0.863406  0.575645      0.518959   0.530978   0.300975
 0.717595   0.716052  0.980421      0.741858   0.283028   0.443185
 0.343585   0.158744  0.224098      0.20299  

**Note:  Other ways to build matrices**
* use hcat and vcat to concatenate vectors together horizontally or vertically
* use ones() or zeros(m, n) to create a m by n matrix of either ones or zeros
* use Diagonal(M) to create a diagonal matrix from a vector M
* Random functions
    * rand(m, n) makes an m by n matrix of random numbers from a uniform distribution 0-1
    * randn(m, n) m by n matrix from a standard normal distribution
    * rand(X, m, n) m by n matrix of random numbers in an array X
* use reshape(X, m, n) to turn a vector X into a matrix size m by n
* use repeat(X, m ,n) to repeat matrix X m times in the row direction and n times in the column direction

### Problem 4.
**a) return the biggest number in the matrix bigNumbers with indexing**

In [16]:
bigNumbers = [1 34 6 56 7 234 6 5; 3 43635 2 35 6 234 6 23; 235 56 2 46 56 3 234 6; 87 23 8 23 9 47 0 8]

biggestNum = bigNumbers[2,2] #fill this in 
smallestNum = bigNumbers[4,7] #fill this in

#return the biggest number and the smallest number in the matrix  
println("Biggest: ", biggestNum, ", Smallest: ", smallestNum)

Biggest: 43635, Smallest: 0


**b) return the column containing the biggest number as a column vector**

Hint:  In indexing, the colon : operator in place of a row or column indicates that all the rows/columns will be selected

In [17]:
bigColumn = bigNumbers[:,2] #fill this in

4-element Vector{Int64}:
    34
 43635
    56
    23

**c) return the row containing the biggest number as a row vector**

Hint:  You will probably need to transpose this vector.  Julia will automatically return a column vector, even though you are selecting a row, so you will need to transpose to convert it to a row vector with a single quote( ' ) after the vector statement.


In [18]:
#Example of transposing
@show Z = [1, 2, 3, 4]  #Z is a column vector
@show Z'
#Z' is a row vector

Z = [1, 2, 3, 4] = [1, 2, 3, 4]
Z' = [1 2 3 4]

1×4 adjoint(::Vector{Int64}) with eltype Int64:
 1  2  3  4

In [21]:
bigRow = bigNumbers[2,:] 
@show bigRow'#fill this in

bigRow' = [3 43635 2 35 6 234 6 23]

1×8 adjoint(::Vector{Int64}) with eltype Int64:
 3  43635  2  35  6  234  6  23

#### Elements of an Array vs Scalars
In Julia, there is a difference in type between a 1x1 matrix and a number.  Silly and annoying, but easy to fix.  By using indexing, we can take the number out of the matrix.  We simply use matrix[1]

### Problem 5.
Extract the number from the 1x1 matrix

In [22]:
tinyMatrix = [7.01]

#output the number inside as a Float64
numberInside = tinyMatrix[1,1] #fill in

7.01

### Problem 6
This 3 by 3 System of linear equations is from Problem 3 of the written homework.

$$ 4x_1  = 8 $$
$$  2x_1 - 10x_2 = -2 $$
$$ x_1 + 2x_2 - x_3 = 4 $$

**a) Create matrices A and b so that Ax = b represents this 3 by 3 system.  x = [x1; x2; x3]**

In [23]:
#replace each underscore with a number
@show A = [4 0 0 ;  2 -10 0 ; 1 2 -1]
@show b = [8 ; -2 ; 4]

A = [4 0 0; 2 -10 0; 1 2 -1] = [4 0 0; 2 -10 0; 1 2 -1]
b = [8; -2; 4] = [8, -2, 4]


3-element Vector{Int64}:
  8
 -2
  4

Now that you found the matrices that define this system, the algorithm below shows how we can use forward substitution in code to solve for the x vector.  
**b) Display the vector x in the output window with whatever method you prefer**

In [24]:
x = [0.0; 0.0; 0.0] #Initialize an empty x vector

#This method does not scale to large problems, but it is super clear
x[1]=b[1]/A[1,1]
x[2]=(b[2]-A[2,1]*x[1])/A[2,2]
x[3]=(b[3]-A[3,1]*x[1]-A[3,2]*x[2])/A[3,3]
;
@show x
#add a line here that will display the vector x

x = [2.0, 0.6, -0.8]


3-element Vector{Float64}:
  2.0
  0.6
 -0.8

### Problem 7
**Now, modify the algorithm above to work for a 5 by 5 system.**

$$ 4x_1  = 8 $$
$$  2x_1 - 10x_2 = -2 $$
$$ x_1 + 2x_2 - x_3 = 4 $$
$$ 4x_1 - x_2 - 3x_3 + x_4 = 7 $$
$$ -2x_1 + 7x_2 + x_3 - 2x_4 - 6x_5 = 12 $$


In [25]:
#first, declare your A and b
A = [4 0 0 0 0; 2 -10 0 0 0; 1 2 -1 0 0; 4 -1 -3 1 0; -2 7 1 -2 -6]
b = [8; -2; 4; 7; 12]

5-element Vector{Int64}:
  8
 -2
  4
  7
 12

In [26]:
x = Vector{Float64}(undef, 5)  #this time, x will be a vector of 5 entries(this is another way to start a vector)

#now, modify the algorithm to work on this 5 by 5 system by adding two more equations.
x[1]=b[1]/A[1,1]
x[2]=(b[2]-A[2,1]*x[1])/A[2,2]
x[3]=(b[3]-A[3,1]*x[1]-A[3,2]*x[2])/A[3,3]
x[4]=(b[4]-A[4,1]*x[1]-A[4,2]*x[2]-A[4,3])/A[4,4]
x[5]=(b[5]-A[5,1]*x[1]-A[5,2]*x[2]-A[5,3]*x[3]-A[5,4])/A[5,5]

-2.4333333333333336

**That was super tedious, right? If not, then we failed. You were supposed to go, what are they thinking, there must be a better way to go about this!! Yes, there is. ** 

### A Better Algorithm!

But first, let's generate some data to set you up for success. Run the next cell. There is nothing to report. 

In [27]:
# Execute this line to define A, b and x before you move on 
x = [0.0; 0.0; 0.0] #Initialize an empty x vector
A=[4.0 2.1 1.0; -7.03 1.0/3.0 π; 2.7 -18.1 -11.11]
b=[15.0 13.6 -21.2]'

3×1 adjoint(::Matrix{Float64}) with eltype Float64:
  15.0
  13.6
 -21.2

**The problem with the "steps" in the previous cell is that each line of calculation is different from the others. That makes it hard to "automate", which is what programming is all about right? We humans set up the program and we let the computer automtically grind through the computations?**

Let's focus on the very first line of the forward substitution method
$$ x[1]=b[1]/A[1,1] $$

Suppose that we set x to be a zero column vector with three elements 
$$ x=[0.0;0.0;0.0] $$ 

You know that $ A[1,:]'$ is the first ROW of the A matrix

What will be the result of 
$ A[1,:] '*x $ ?

Because x is the zero vector we get zero. We weren't trying to fool you, just making you admit the obvious.

Hence if we could write something like
$$ x[1]=(b[1] -  A[1,:]' *x )/A[1,1] $$
we woudl get the same result as
$$ x[1]=b[1]/A[1,1] $$
which is the first step of forward substitution. Let's note that we have updated the value of $ x[1] $, while $ x[2] $ and $ x[3] $ remain zero. Why is this important? 

Well, ask yourself, what will be the result of the multiplication  of the Second row of A times x?
$$ A[2,:] '*x $$   
                                                
once again, knowing that $ x[2]=0 $ and $ x[3]=0 $ ?

Because only $x[1]$ is potentially non-zero, we have $A[2,1]*x[1]$

Hence if we could write something like
$$x[2]=(b[2] -  A[2,:]' *x )/A[2,2]$$
we would get the same result as
$$x[2]=(b[2]-A[2,1]*x[1])/A[2,2]$$

Hopefully you see the pattern, if we could write something like 
$$x[3]=(b[3] -  A[3,:]' *x )/A[3,3]$$
we'd get the same result as 
$$x[3]=(b[3]-A[3,1]*x[1]-A[3,2]*x[2])/A[3,3]$$

Now, all of our lines of code look the same. Therefore, we can automate them! 

There is one catch, which maybe you already noted: in Julia a row vector times a column vector (of the same lengths) gives a 1x1 matrix, which is not the same thing as a scalar (that is, a number). So, we have to extract out (or slice out) that number via: 
$$ (A[k,:])' * x)[1]$$

You may need to go back to the top and look at Problem 5 and tinyMatrix.

In the next cell, you can run the two sets of equations and verify that we get the same answers. 

In [28]:
# New way where there is a pattern
x=[0.0;0.0;0.0]
x[1]=(b[1]-(A[1,:]' *x)[1])/A[1,1]
x[2]=(b[2]-(A[2,:]' *x)[1])/A[2,2]
x[3]=(b[3]-(A[3,:]' *x)[1])/A[3,3]
@show x
# Old way where each line is different
xx=[0.0;0.0;0.0]
xx[1]=b[1]/A[1,1]
xx[2]=(b[2]-A[2,1]*xx[1])/A[2,2]
xx[3]=(b[3]-A[3,1]*xx[1]-A[3,2]*xx[2])/A[3,3]
@show xx

x = [3.75, 119.8875, -192.49673717371743]
xx = [3.75, 119.8875, -192.49673717371743]


3-element Vector{Float64}:
    3.75
  119.8875
 -192.49673717371743

We're almost at a crucial point of having our first real program. **Almost!** 

We'll let you grind a bit more! Ouch! 

### Problem 8.
For a system of equations Ax = b that is bigger, for example, 10x10, it would make more sense to have some sort of repeating code, than to type 10 equations. We've seen that our magic common equation has the form

$$x[k]=(b[k]-(A[k,:]' *x)[1])/A[k,k]$$ 

For this problem, we will give you a large A and b. You assume that Ax = b, and that x is a column vector with 10 entries. We'll have you MANUALLY repeat a step 10 times! (Hey, it's better than typing 10 equations!)

In [29]:
#Run this cell to generate matrices A and b, and initialize x to be the correct size.  DO NOT MODIFY IT!
#Once it is done running, you should see a 10x10 lower triangular matrix as the output


using Pkg
Pkg.add("Random")
using Random
Random.seed!(1234)
N=10; A=rand(N,N); #Builds a 10 x 10 matrix filled with randon elements, except, we fixed the 
# "seed" so that all of you will generate the same matrix

# Make A lower triangular with one for loop and indexing
# For now, pretend that you have not seen the command "for" and its friend "end"
for k=1:N
    A[k,k+1:N]=0.0* A[k,k+1:N]; #Not important to understand this line at this TIME!
end 
b=rand(N,1); # a random column vector of size 10 x 1. Not bad.
x=0*b; # Sets x to zero and has the same size as b
@show size(x)
A

size(x) = (10, 1)

    Updating registry at `C:\Users\qpow3\.julia\registries\General.toml`
   Resolving package versions...
    Updating `C:\Users\qpow3\.julia\environments\v1.7\Project.toml`
  [9a3f8284] + Random
  No Changes to `C:\Users\qpow3\.julia\environments\v1.7\Manifest.toml`


10×10 Matrix{Float64}:
 0.579862   0.0       0.0        0.0       …  0.0       0.0       0.0
 0.411294   0.536369  0.0        0.0          0.0       0.0       0.0
 0.972136   0.711389  0.966197   0.0          0.0       0.0       0.0
 0.0149088  0.103929  0.666558   0.91097      0.0       0.0       0.0
 0.520355   0.806704  0.333859   0.973653     0.0       0.0       0.0
 0.639562   0.870539  0.802199   0.76066   …  0.0       0.0       0.0
 0.839622   0.962715  0.156458   0.488912     0.0       0.0       0.0
 0.967143   0.15118   0.380799   0.362643     0.813512  0.0       0.0
 0.789764   0.715355  0.0687591  0.708738     0.994935  0.566878  0.0
 0.696041   0.939548  0.861725   0.656694     0.77916   0.607905  0.67765

Now, to find all the values of x, we can define an equation that looks like our  algorithm above, 
$$ x[k]=(b[k]-(A[k,:]' *x)[1])/A[k,k]  $$  
and run it 10 times.

In [30]:
#first we need to start a counter variable to count the times that we have run the loop and so that we can index into the
# x vector
k = 0

0

In [40]:
#you will need to run this block of code for EVERY ROW of the matrix A (10 times).  
#Each output will correspond to an entry in the x vector.  Enter them in the block below for grading.
k = k + 1
x[k] = (b[k]-((A[k , :]') *x)[1])/A[k,k]
print(k)
print(x[k])

#hint: If you get a BoundsError, re-run the cell above to reset k to zero. 
#you will also need to re-run the initialization cell

102.8352630459174732

In [41]:
#Enter your results here:
x1 = 10.14389643078051334
x2 = 20.8699464053244844
x3 = 30.08474825885481517
x4 = 40.4115390578275809
x5 = 5-2.8306691942374544
x6 = 62.244642297318368
x7 = 7-0.09193033809617719
x8 = 80.5010235678535924
x9 = 9-4.971866009002309
x10 = 102.8352630459174732
;

#### Using the inv() function of the Linear Algebra package.  
This function takes in the matrix A and the vector b, and returns the solution vector x.  No, this is not cheating, it is checking your work!  The cell below should return the same vector as your solution to the cell above.

In [42]:
#Your results should match this
using LinearAlgebra
inv(A)*b

10×1 Matrix{Float64}:
  0.14389643078051334
  0.8699464053244844
  0.08474825885481518
  0.41153905782758093
 -2.830669194237455
  2.2446422973183697
 -0.09193033809617734
  0.5010235678535905
 -4.971866009002307
  2.835263045917472

#### What if, instead of running that cell over and over manually, we used a control flow operator to do it for us?  For loops are perfect for running a certain number of times, and they even keep track of the counter variable for us.

### Problem 9
Find the solution to a 100 by 100 system! 

In [43]:
# This generates the matrices A and b for a 100x100 system.  DO NOT MODIFY THIS CELL!

Random.seed!(4321)
N=100; A=rand(N,N);
# Make A lower triangular with one for loop and indexing

# This time, pay attention to "for" and its friend "end". Everything in between is repeated for k=1 all the way 
# up to k=N. How convenient is that? (Yes, we know, when we first learned this we were bowled over too!)

for k=1:N  
    A[k,k+1:N]=0.0* A[k,k+1:N]; #Not important to understand this line at this TIME!
end 
b=rand(N,1);
x=0*b;  #makes an x vector the same size as the b vector, but full of zeros


In [46]:
for k=1:N
    x[k] = (b[k]-((A[k , :]') *x)[1])/A[k,k] #fill this in!! Hint: Look at the cell you repeated earlier!
end
print(x[1:10, 1]) #show the first 10 entries of x

[2.4008493528980432, 1.5029748079688743, -0.748628422459897, -1.1810509849044308, -16.12376549117034, 16.7731779923699, 3.341099653317763, 20.521388535237246, -9.475640685159632, 8.46453771729228]

#### Check your work with the inv() function.

In [47]:
#the inv() function
ansComp = inv(A)*b
print(x[1:10, 1])
isapprox(x, ansComp) #this function will tell us if the computer got the same values with inv() as we did with the algorithm
#if it returns "true" then your algorithm worked! 
#Otherwise, try again, and make sure to re-run the cell that builds the matrices to get a fresh start.

[2.4008493528980432, 1.5029748079688743, -0.748628422459897, -1.1810509849044308, -16.12376549117034, 16.7731779923699, 3.341099653317763, 20.521388535237246, -9.475640685159632, 8.46453771729228]

true

Cheatsheets for Julia Vector and Matrix syntax
* https://cheatsheets.quantecon.org/julia-cheatsheet.html#vectors-and-matrices
* https://www.softcover.io/read/7b8eb7d0/juliabook/basics

Documentation for the LinearAlgebra Package
* https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/